pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('SonarQube analysis') {
            steps {
                def scannerHome = tool 'SonarScanner 4.0';
                withSonarQubeEnv('SonarQube') { // If you have configured more than one global server connection, you can specify its name
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('deploy stage'){
            steps {
                            sh 'echo "deploy stage"'
                        }
        }
    }
}
